export { VERSES };

class Verse {
  constructor(ref, words) {
    this.ref = ref;
    this.words = words;
    this.text = words.map(x => x[0]).join(' ');
  }
}

const VERSES = [
  new Verse('Mark 1:1', [['Ἀρχὴ', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'feminine'}], ['τοῦ', {'part of speech': 'article', 'case': 'genitive', 'number': 'singular', 'gender': 'neuter'}], ['εὐαγγελίου', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'neuter'}], ['Ἰησοῦ', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'masculine'}], ['Χριστοῦ,', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'masculine'}]]),
  new Verse('John 6:48', [['ἐγώ', {'part of speech': 'personal pronoun', 'person': 'first person', 'case': 'nominative', 'number': 'singular'}], ['εἰμι', {'part of speech': 'verb', 'tense': 'present', 'voice': 'active', 'mood': 'indicative', 'person': 'first person', 'number': 'singular'}], ['ὁ', {'part of speech': 'article', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['ἄρτος', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['τῆς', {'part of speech': 'article', 'case': 'genitive', 'number': 'singular', 'gender': 'feminine'}], ['ζωῆς.', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'feminine'}]]),
  new Verse('John 1:1', [['Ἐν', {'part of speech': 'preposition'}], ['ἀρχῇ', {'part of speech': 'noun', 'case': 'dative', 'number': 'singular', 'gender': 'feminine'}], ['ἦν', {'part of speech': 'verb', 'tense': 'imperfect', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'singular'}], ['ὁ', {'part of speech': 'article', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['λόγος,', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['καὶ', {'part of speech': 'conjunction'}], ['ὁ', {'part of speech': 'article', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['λόγος', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['ἦν', {'part of speech': 'verb', 'tense': 'imperfect', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'singular'}], ['πρὸς', {'part of speech': 'preposition'}], ['τὸν', {'part of speech': 'article', 'case': 'accusative', 'number': 'singular', 'gender': 'masculine'}], ['θεόν,', {'part of speech': 'noun', 'case': 'accusative', 'number': 'singular', 'gender': 'masculine'}], ['καὶ', {'part of speech': 'conjunction'}], ['θεὸς', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['ἦν', {'part of speech': 'verb', 'tense': 'imperfect', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'singular'}], ['ὁ', {'part of speech': 'article', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['λόγος.', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}]]),
  new Verse('Gal 1:24', [['καὶ', {'part of speech': 'conjunction'}], ['ἐδόξαζον', {'part of speech': 'verb', 'tense': 'imperfect', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'plural'}], ['ἐν', {'part of speech': 'preposition'}], ['ἐμοὶ', {'part of speech': 'personal pronoun', 'person': 'first person', 'case': 'dative', 'number': 'singular'}], ['τὸν', {'part of speech': 'article', 'case': 'accusative', 'number': 'singular', 'gender': 'masculine'}], ['θεόν.', {'part of speech': 'noun', 'case': 'accusative', 'number': 'singular', 'gender': 'masculine'}]]),
  new Verse('Matt 12:8', [['κύριος', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['γάρ', {'part of speech': 'conjunction'}], ['ἐστιν', {'part of speech': 'verb', 'tense': 'present', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'singular'}], ['τοῦ', {'part of speech': 'article', 'case': 'genitive', 'number': 'singular', 'gender': 'neuter'}], ['σαββάτου', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'neuter'}], ['ὁ', {'part of speech': 'article', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['υἱὸς', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['τοῦ', {'part of speech': 'article', 'case': 'genitive', 'number': 'singular', 'gender': 'masculine'}], ['ἀνθρώπου.', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'masculine'}]]),
  new Verse('Luke 6:5', [['καὶ', {'part of speech': 'conjunction'}], ['ἔλεγεν', {'part of speech': 'verb', 'tense': 'imperfect', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'singular'}], ['αὐτοῖς', {'part of speech': 'personal pronoun', 'case': 'dative', 'number': 'plural', 'gender': 'masculine'}], ['ὅτι', {'part of speech': 'conjunction'}], ['κύριός', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['ἐστιν', {'part of speech': 'verb', 'tense': 'present', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'singular'}], ['ὁ', {'part of speech': 'article', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['υἱὸς', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['τοῦ', {'part of speech': 'article', 'case': 'genitive', 'number': 'singular', 'gender': 'masculine'}], ['ἀνθρώπου', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'masculine'}], ['καὶ', {'part of speech': 'conjunction'}], ['τοῦ', {'part of speech': 'article', 'case': 'genitive', 'number': 'singular', 'gender': 'neuter'}], ['σαββάτου.', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'neuter'}]]),
  new Verse('1 Cor 3:23', [['ὑμεῖς', {'part of speech': 'personal pronoun', 'person': 'second person', 'case': 'nominative', 'number': 'plural'}], ['δὲ', {'part of speech': 'conjunction'}], ['Χριστοῦ,', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'masculine'}], ['Χριστὸς', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['δὲ', {'part of speech': 'conjunction'}], ['θεοῦ.', {'part of speech': 'noun', 'case': 'genitive', 'number': 'singular', 'gender': 'masculine'}]]),
  new Verse('John 7:5', [['οὐδὲ', {'part of speech': 'conjunction', 'extra': 'negative'}], ['γὰρ', {'part of speech': 'conjunction'}], ['οἱ', {'part of speech': 'article', 'case': 'nominative', 'number': 'plural', 'gender': 'masculine'}], ['ἀδελφοὶ', {'part of speech': 'noun', 'case': 'nominative', 'number': 'plural', 'gender': 'masculine'}], ['αὐτοῦ', {'part of speech': 'personal pronoun', 'case': 'genitive', 'number': 'singular', 'gender': 'masculine'}], ['ἐπίστευον', {'part of speech': 'verb', 'tense': 'imperfect', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'plural'}], ['εἰς', {'part of speech': 'preposition'}], ['αὐτόν.', {'part of speech': 'personal pronoun', 'case': 'accusative', 'number': 'singular', 'gender': 'masculine'}]]),
  new Verse('John 17:17', [['ἁγίασον', {'part of speech': 'verb', 'tense': 'aorist', 'voice': 'active', 'mood': 'imperative', 'person': 'second person', 'number': 'singular'}], ['αὐτοὺς', {'part of speech': 'personal pronoun', 'case': 'accusative', 'number': 'plural', 'gender': 'masculine'}], ['ἐν', {'part of speech': 'preposition'}], ['τῇ', {'part of speech': 'article', 'case': 'dative', 'number': 'singular', 'gender': 'feminine'}], ['ἀληθείᾳ·', {'part of speech': 'noun', 'case': 'dative', 'number': 'singular', 'gender': 'feminine'}], ['ὁ', {'part of speech': 'article', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['λόγος', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['ὁ', {'part of speech': 'article', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['σὸς', {'part of speech': 'possessive pronoun', 'person': 'second person', 'possessor number': 'singular possessor', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['ἀλήθειά', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'feminine'}], ['ἐστιν.', {'part of speech': 'verb', 'tense': 'present', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'singular'}]]),
  new Verse('Mark 3:15', [['καὶ', {'part of speech': 'conjunction'}], ['ἔχειν', {'part of speech': 'verb', 'tense': 'present', 'voice': 'active', 'mood': 'infinitive'}], ['ἐξουσίαν', {'part of speech': 'noun', 'case': 'accusative', 'number': 'singular', 'gender': 'feminine'}], ['ἐκβάλλειν', {'part of speech': 'verb', 'tense': 'present', 'voice': 'active', 'mood': 'infinitive'}], ['τὰ', {'part of speech': 'article', 'case': 'accusative', 'number': 'plural', 'gender': 'neuter'}], ['δαιμόνια·', {'part of speech': 'noun', 'case': 'accusative', 'number': 'plural', 'gender': 'neuter'}]]),
  new Verse('Acts 13:30', [['ὁ', {'part of speech': 'article', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['δὲ', {'part of speech': 'conjunction'}], ['θεὸς', {'part of speech': 'noun', 'case': 'nominative', 'number': 'singular', 'gender': 'masculine'}], ['ἤγειρεν', {'part of speech': 'verb', 'tense': 'aorist', 'voice': 'active', 'mood': 'indicative', 'person': 'third person', 'number': 'singular'}], ['αὐτὸν', {'part of speech': 'personal pronoun', 'case': 'accusative', 'number': 'singular', 'gender': 'masculine'}], ['ἐκ', {'part of speech': 'preposition'}], ['νεκρῶν·', {'part of speech': 'adjective', 'case': 'genitive', 'number': 'plural', 'gender': 'masculine'}]]),
];

